apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: ai-team-dev
data:
  # APIサーバー関連設定
  API_HOST: "ai-team-api-server.ai-team-dev.svc.cluster.local"
  API_PORT: "8000"
  
  # ベクトルDB関連設定
  VECTOR_DB_HOST: "ai-team-vector-db.ai-team-dev.svc.cluster.local"
  VECTOR_DB_PORT: "8000"
  
  # メトリクス関連設定
  METRICS_HOST: "ai-team-metrics-service.ai-team-dev.svc.cluster.local"
  METRICS_PORT: "9090"
  
  # トレース関連設定
  TRACE_HOST: "ai-team-traces-service.ai-team-dev.svc.cluster.local"
  TRACE_PORT: "4317"
  
  # ログ関連設定
  LOG_HOST: "ai-team-logs-service.ai-team-dev.svc.cluster.local"
  LOG_PORT: "9200"
  
  # その他共通設定
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: "/app" 