apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-team-main-app
  namespace: ai-team-dev
  labels:
    app: ai-team-main-app
    component: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-team-main-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-team-main-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: main-app
        image: ${REGISTRY_URL}/ai-team-main-app:latest  # ビルド時に実際の値に置換
        imagePullPolicy: Always
        command: ["python", "main.py"]
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: app-specific-config
        - secretRef:
            name: api-keys
        volumeMounts:
        - name: artifacts
          mountPath: /app/artifacts
        - name: logs
          mountPath: /app/logs
        - name: storage
          mountPath: /app/storage
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import os; exit(0 if os.path.exists('/app/logs/main.log') else 1)"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import os; exit(0 if os.path.exists('/app/logs/main.log') else 1)"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: artifacts
        persistentVolumeClaim:
          claimName: ai-team-artifacts-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: ai-team-logs-pvc
      - name: storage
        persistentVolumeClaim:
          claimName: ai-team-storage-pvc 