apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: ai-team-dev-cluster
  namespace: ai-team-dev-infra
  annotations:
    cnrm.cloud.google.com/project-id: "ai-team-dev-project"
spec:
  description: "AIエージェントチーム開発用GKEクラスタ"
  location: asia-northeast1
  initialNodeCount: 1
  networkingMode: VPC_NATIVE
  workloadIdentityConfig:
    workloadPool: "ai-team-dev-project.svc.id.goog"
  releaseChannel:
    channel: REGULAR
  nodeConfig:
    machineType: e2-standard-4
    oauthScopes:
    - "https://www.googleapis.com/auth/cloud-platform"
    tags:
    - "ai-team-dev"
  networkRef:
    name: ai-team-dev-vpc
  subnetworkRef:
    name: ai-team-dev-subnet
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: "0.0.0.0/0"
      displayName: "all"
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  addonsConfig:
    httpLoadBalancing:
      disabled: false
    horizontalPodAutoscaling:
      disabled: false
    networkPolicyConfig:
      disabled: false
  networkPolicy:
    enabled: true
    provider: CALICO
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: ai-team-dev-node-pool
  namespace: ai-team-dev-infra
  annotations:
    cnrm.cloud.google.com/project-id: "ai-team-dev-project"
spec:
  location: asia-northeast1
  clusterRef:
    name: ai-team-dev-cluster
  nodeCount: 3
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 5
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    machineType: e2-standard-4
    diskSizeGb: 100
    diskType: pd-standard
    labels:
      env: production
      app: ai-team-dev
    oauthScopes:
    - "https://www.googleapis.com/auth/cloud-platform"
    workloadMetadataConfig:
      mode: GKE_METADATA 