apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: ai-team-dev-artifacts
  namespace: ai-team-dev-infra
  annotations:
    cnrm.cloud.google.com/project-id: "ai-team-dev-project"
spec:
  location: asia-northeast1
  versioning:
    enabled: true
  lifecycleRule:
  - action:
      type: Delete
    condition:
      age: 365
      numNewerVersions: 3
  uniformBucketLevelAccess: true
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: ai-team-dev-logs
  namespace: ai-team-dev-infra
  annotations:
    cnrm.cloud.google.com/project-id: "ai-team-dev-project"
spec:
  location: asia-northeast1
  lifecycleRule:
  - action:
      type: Delete
    condition:
      age: 90
  uniformBucketLevelAccess: true
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: ai-team-dev-api-keys
  namespace: ai-team-dev-infra
  annotations:
    cnrm.cloud.google.com/project-id: "ai-team-dev-project"
spec:
  replication:
    automatic: true
---
apiVersion: cloudkms.cnrm.cloud.google.com/v1beta1
kind: CloudKMSKeyRing
metadata:
  name: ai-team-dev-keyring
  namespace: ai-team-dev-infra
  annotations:
    cnrm.cloud.google.com/project-id: "ai-team-dev-project"
spec:
  location: global
---
apiVersion: cloudkms.cnrm.cloud.google.com/v1beta1
kind: CloudKMSCryptoKey
metadata:
  name: ai-team-dev-secrets-key
  namespace: ai-team-dev-infra
  annotations:
    cnrm.cloud.google.com/project-id: "ai-team-dev-project"
spec:
  purpose: ENCRYPT_DECRYPT
  keyRingRef:
    name: ai-team-dev-keyring
  rotationPeriod: 7776000s  # 90日
  versionTemplate:
    algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
    protectionLevel: SOFTWARE 